<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<OutputPath>bin\Release\net8.0\</OutputPath>
    <!--<TargetFramework>net6.0</TargetFramework>-->
	<TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

		<ItemGroup>
			<PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
			<PackageReference Include="Microsoft.AspNet.Mvc" Version="5.2.8" />
			<PackageReference Include="DocsVision.BackOffice.ObjectModel" Version="6.1.223" />
			<PackageReference Update="DocsVision.*" ExcludeAssets="contentFiles" />
			<PackageReference Include="DocsVision.WebClient.Extensibility" Version="6.1.716" />
			<PackageReference Include="Scrutor" Version="4.2.2" />
			<PackageReference Include="DocsVision.BackOffice.Cards.Web" Version="6.1.716" />
			<PackageReference Include="DocsVision.Platform" Version="6.1.374" />
			<PackageReference Include="DocsVision.Platform.CardLib" Version="6.1.374" />
			<PackageReference Include="DocsVision.Platform.ObjectManager.Rest" Version="6.1.374" />
			<PackageReference Include="DocsVision.Platform.ObjectModel" Version="6.1.374" />
			<PackageReference Include="DocsVision.Platform.StorageServer" Version="6.1.374" />
			<PackageReference Include="DocsVision.Platform.SystemCards.ObjectModel" Version="6.1.374" />
			<PackageReference Include="DocsVision.Platform.SystemObjects" Version="6.1.374" />
			<PackageReference Include="DocsVision.Platform.Xml.Schemas" Version="6.1.374" />
			<PackageReference Include="DocsVision.Platform.WebClient" Version="6.1.716" />
			<PackageReference Include="DocsVision.WebFrame.WebClient" Version="6.1.716" />
			<PackageReference Include="DocsVision.WebClientLibrary.ObjectModel" Version="6.1.716" />
			<PackageReference Update="DocsVision.*" ExcludeAssets="contentFiles" IncludeAssets="compile" />

		</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="DocsVision.WebClient.Extensibility" Version="6.1.716" />
	</ItemGroup>

</Project>
